# oh yea
[dependencies]
c="0"
d="0"
a="0"
b="0"

[dependencies.alpha]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dependencies.beta]
version = "0.15"
# oh yea
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

# oh yea
[dependencies.syn]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

# oh yea
